on:
  push:
    tags: [ 'v*.*.*' ]

name: deploy

jobs:
  check:
    name: CI Suite
    runs-on: ubuntu-latest

    steps:
      - name: Checkout sources
        uses: actions/checkout@v6

      - name: Install Rust 
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable

      - name: Setup Cache
        uses: Swatinem/rust-cache@v2

      - name: Build Release
        run: cargo build --release
        shell: bash

      - name: Install cargo-audit
        run: cargo install cargo-audit --locked
        shell: bash

      - name: Audit
        run: cargo audit
        shell: bash

      - name: Install cargo-semver-checks
        run: cargo install cargo-semver-checks --locked
        shell: bash

      - name: Semver Check
        run: cargo semver-checks
        shell: bash

      - name: Publish
        run: cargo publish --locked --token ${{ secrets.CratesToken }}
        shell: bash